apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: mbuaku/purpose-planner-services/gateway-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: FINANCIAL_SERVICE_URL
          value: "http://financial-service:3002"
        - name: SPIRITUAL_SERVICE_URL
          value: "http://spiritual-service:3003"
        - name: PROFILE_SERVICE_URL
          value: "http://profile-service:3004"
        - name: SCHEDULE_SERVICE_URL
          value: "http://schedule-service:3005"
        - name: DASHBOARD_SERVICE_URL
          value: "http://dashboard-service:3006"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: development
spec:
  selector:
    app: gateway-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort