apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  namespace: development
  labels:
    app: gateway-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
      - name: gateway-service
        image: mbuaku/purpose-planner-services:gateway-service-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3001"
        - name: PROFILE_SERVICE_URL
          value: "http://profile-service:3004"
        - name: DASHBOARD_SERVICE_URL
          value: "http://dashboard-service:3006"
        - name: FINANCIAL_SERVICE_URL
          value: "http://financial-service:3002"
        - name: SCHEDULE_SERVICE_URL
          value: "http://schedule-service:3005"
        - name: SPIRITUAL_SERVICE_URL
          value: "http://spiritual-service:3003"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
---
# Service to expose Gateway API
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: development
  labels:
    app: gateway-service
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: gateway-service