apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
      - name: profile-service
        image: mbuaku/purpose-planner-services/profile-service:latest
        ports:
        - containerPort: 3004
        env:
        - name: PORT
          value: "3004"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: development
spec:
  selector:
    app: profile-service
  ports:
  - port: 3004
    targetPort: 3004
  type: ClusterIP